Bash scripts: `shellcheck`’d, `set -euo pipefail`, & other cleanup

diff --git a/src/videbcontrol b/src/videbcontrol
--- a/src/videbcontrol
+++ b/src/videbcontrol
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -euo pipefail
+
 # Edit control file inside DEBs to fix dependencies
 #
 # Credits: https://ubuntuforums.org/showthread.php?t=636724
@@ -10,8 +12,8 @@ if [[ -z "$1" ]]; then
 fi
 
 DEBFILE="$1"
-TMPDIR=$(mktemp -d /tmp/deb.XXXXXXXXXX) || exit 1
-OUTPUT=$(basename "$DEBFILE" .deb).modfied.deb
+TMPDIR="$(mktemp -d /tmp/deb.XXXXXXXXXX)" || exit 1
+OUTPUT="$(basename "$DEBFILE" .deb).modfied.deb"
 
 if [[ -e "$OUTPUT" ]]; then
     echo "$OUTPUT exists."
@@ -20,24 +22,24 @@ if [[ -e "$OUTPUT" ]]; then
 fi
 
 dpkg-deb -x "$DEBFILE" "$TMPDIR"
-dpkg-deb --control "$DEBFILE" "$TMPDIR"/DEBIAN
+dpkg-deb --control "$DEBFILE" "$TMPDIR/DEBIAN"
 
-if [[ ! -e "$TMPDIR"/DEBIAN/control ]]; then
-    echo DEBIAN/control not found.
+if [[ ! -e "$TMPDIR/DEBIAN/control" ]]; then
+    echo 'DEBIAN/control not found.'
 
     rm -r "$TMPDIR"
     exit 1
 fi
 
-CONTROL="$TMPDIR"/DEBIAN/control
+CONTROL="$TMPDIR/DEBIAN/control"
 
-MOD=$(stat -c "%y" "$CONTROL")
+MOD="$(stat -c "%y" "$CONTROL")"
 editor "$CONTROL" # use the default editor from Debian alternatives
 
 if [[ "$MOD" == $(stat -c "%y" "$CONTROL") ]]; then
-    echo Not modfied.
+    echo 'Not modfied.'
 else
-    echo Building new deb...
+    echo 'Building new deb...'
     dpkg -b "$TMPDIR" "$OUTPUT"
 fi
 
